version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "repository-maintainers"
    assignees:
      - "repository-maintainers"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 10
    target-branch: "master"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]