title: AI Task Manager
description: Transform chaotic AI prompts into structured, executable workflows
url: https://mateuaguilo.com
baseurl: "/ai-task-manager"

# Just the Docs theme configuration
remote_theme: just-the-docs/just-the-docs

# Theme settings
color_scheme: light
search_enabled: true
heading_anchors: true

# Mermaid support (built into Just the Docs)
mermaid:
  version: "10.6.1"

# Navigation
nav_sort: case_sensitive

# Repository link in header
gh_edit_repository: https://github.com/e0ipso/ai-task-manager
gh_edit_branch: main
gh_edit_link: true
gh_edit_link_text: "View on GitHub"

# SEO and social media
author: e0ipso
twitter:
  username: e0ipso

# Jekyll plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Markdown processing
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
      
# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/